CREATE TABLE IF NOT EXISTS relearnedData(
    examId TEXT,
    s1 REAL NOT NULL,
    s2 REAL NOT NULL,
    s3 REAL NOT NULL,
    s4 REAL NOT NULL,
    s5 REAL NOT NULL,
    s6 REAL NOT NULL,
    s7 REAL NOT NULL,
    s8 REAL NOT NULL,
    s9 REAL NOT NULL,
    RECOMMENDATION_IA TEXT NOT NULL,
    FINAL_RECOMMENDATION TEXT
);
